### ISSUE TITLE
how set edit_frame_index = ? 1 2 3 ... ?

### ISSUE THREAD

**Issue by lzhmhznr** [ykasten/layered-neural-atlases#5]
python only_edit.py --trained_model_folder=pretrained_models/checkpoints/libby --video_name=libby --data_folder=data --output_folder=editing_outputs  --use_edit_frame --edit_frame_index=7 --edit_frame_path=pretrained_models/edit_inputs/libby/edit_frame_.png

how set edit_frame_index = ? 1 2 3 ... ?

**Comment by dolev104** [comment]
Frame index is used as an index in a tensor - starting from 0 up until (number of frames in video - 1)

**Comment by goldorach** [comment]
Hello friends me again,I have come this far:

Traceback (most recent call last):
  File "only_edit.py", line 473, in <module>
    frame_edit_index, output_folder, video_name, edit_frame_foreground, edit_frame_background,' '.join(sys.argv))
  File "only_edit.py", line 312, in main
    mask = np.array(Image.open(str(mask_files[i]))).astype(np.float64) / 255.
IndexError: list index out of range

any clue ? i don't have it 
Thank's for your time
