### ISSUE TITLE
ValueError: number sections must be larger than 0

### ISSUE THREAD

**Issue by 616099859** [ykasten/layered-neural-atlases#7]
(neural_atlases) D:\layered-neural-atlases-main>python only_edit.py --trained_mo
del_folder=pretrained_models/checkpoints/libby --video_name=libby --data_folder=
data/libby --output_folder=editing_outputs  --use_edit_frame --edit_frame_index=
7 --edit_frame_path=pretrained_models/edit_inputs/libby/edit_frame_.png

Model has 264706 params
Model has 133122 params
Model has 416379 params
Model has 402945 params
Traceback (most recent call last):
  File "only_edit.py", line 472, in <module>
    main(training_folder, frame_edit, frames_folder, mask_rcnn_folder, frame_edi
t_file, edit_tex1_file, edit_tex2_file,
  File "only_edit.py", line 378, in main
    edit_im1, edit_im2 = texture_edit_from_frame_edit(edit_frame, frame_number,
model_F_mapping1, model_F_mapping2,
  File "only_edit.py", line 204, in texture_edit_from_frame_edit
    maxx2, minx2, maxy2, miny2, edge_size2 = get_mapping_area(model_F_mapping2,
model_alpha, mask_frames > -1, larger_dim,
  File "D:\layered-neural-atlases-main\evaluate.py", line 149, in get_mapping_ar
ea
    relisa = np.array_split(relis_i.numpy(), np.ceil(relis_i.shape[0] / 100000))

  File "<__array_function__ internals>", line 5, in array_split
  File "D:\Anaconda3\envs\neural_atlases\lib\site-packages\numpy\lib\shape_base.
py", line 778, in array_split
    raise ValueError('number sections must be larger than 0.') from None
ValueError: number sections must be larger than 0.

**Comment by ykasten** [comment]
It probably means that the path to the input files is wrong, and therefore the list of video pixels is empty.
